name: iosApp
options:
  bundleIdPrefix: eu.buney
  deploymentTarget:
    iOS: "14.0"
  createIntermediateGroups: true
  defaultConfig: Debug

settings:
  base:
    ENABLE_USER_SCRIPT_SANDBOXING: NO
    DEVELOPMENT_TEAM: ""

targets:
  iosApp:
    type: application
    platform: iOS

    sources:
      - path: iosApp
        excludes:
          - "*.xcodeproj"
          - "*.xcworkspace"

    settings:
      base:
        PRODUCT_NAME: MapsDemo
        PRODUCT_BUNDLE_IDENTIFIER: eu.buney.maps.sample
        INFOPLIST_FILE: iosApp/Info.plist
        FRAMEWORK_SEARCH_PATHS:
          - $(inherited)
          - $(SRCROOT)/../sample/build/xcode-frameworks/$(CONFIGURATION)/$(PLATFORM_NAME)
        SWIFT_VERSION: 5.0
        TARGETED_DEVICE_FAMILY: "1,2"
        LD_RUNPATH_SEARCH_PATHS:
          - $(inherited)
          - "@executable_path/Frameworks"

    preBuildScripts:
      - name: Build Kotlin Framework
        script: |
          export JAVA_HOME="/Applications/Android Studio.app/Contents/jbr/Contents/Home"
          cd "$SRCROOT/.."
          ./gradlew :sample:embedAndSignAppleFrameworkForXcode

          # Create symlink to framework for easier linking
          FRAMEWORK_DIR="sample/build/xcode-frameworks/$CONFIGURATION"
          if [ -d "$FRAMEWORK_DIR" ]; then
            # Find the actual framework directory (with SDK version)
            ACTUAL_DIR=$(find "$FRAMEWORK_DIR" -type d -name "${PLATFORM_NAME}*" -maxdepth 1 | head -n 1)
            if [ -n "$ACTUAL_DIR" ]; then
              # Create symlink without SDK version
              ln -sfn "$(basename "$ACTUAL_DIR")" "$FRAMEWORK_DIR/$PLATFORM_NAME"
            fi
          fi
        basedOnDependencyAnalysis: false

    dependencies:
      - framework: ../sample/build/xcode-frameworks/$(CONFIGURATION)/$(PLATFORM_NAME)/SampleApp.framework
        embed: true

schemes:
  iosApp:
    build:
      targets:
        iosApp: all
    run:
      config: Debug
    profile:
      config: Release
    analyze:
      config: Debug
    archive:
      config: Release
