package eu.buney.maps

/**
 * Represents a set of custom styling options for a Google Map.
 *
 * Use [MapStyleOptions.fromJson] to create an instance from a JSON string generated by the
 * [Google Maps Styling Wizard](https://mapstyle.withgoogle.com/).
 * Both Android and iOS support the same JSON format.
 */
expect class MapStyleOptions {
    companion object {
        /**
         * Creates a [MapStyleOptions] from a JSON string.
         *
         * @param json A valid Google Maps style JSON string.
         * @throws IllegalStateException if the JSON is invalid (iOS only; Android validates lazily).
         */
        fun fromJson(json: String): MapStyleOptions
    }
}
